# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Event.proto',
  package='PB_Event',
  serialized_pb='\n\x0b\x45vent.proto\x12\x08PB_Event\"/\n\x0cPGlobalPoint\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\"\xb8\x01\n\x04PHit\x12(\n\x08position\x18\x01 \x02(\x0b\x32\x16.PB_Event.PGlobalPoint\x12,\n\x0c\x64\x65tectorType\x18\x02 \x02(\x0e\x32\x16.PB_Event.DetectorType\x12\r\n\x05layer\x18\x03 \x02(\x04\x12\x12\n\ndetectorId\x18\x04 \x02(\x04\x12\r\n\x05hitId\x18\x05 \x02(\x04\x12\x12\n\nsimTrackID\x18\x06 \x01(\x04\x12\x12\n\nsimTrackPt\x18\x07 \x01(\x02\"c\n\x06PEvent\x12\x11\n\trunNumber\x18\x01 \x02(\x04\x12\x13\n\x0blumiSection\x18\x02 \x02(\x04\x12\x13\n\x0b\x65ventNumber\x18\x03 \x02(\x04\x12\x1c\n\x04hits\x18\x04 \x03(\x0b\x32\x0e.PB_Event.PHit\"3\n\x0fPEventContainer\x12 \n\x06\x65vents\x18\x01 \x03(\x0b\x32\x10.PB_Event.PEvent*>\n\x0c\x44\x65tectorType\x12\x15\n\x08\x42\x41\x43KWARD\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\n\n\x06\x42\x41RREL\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01')

_DETECTORTYPE = descriptor.EnumDescriptor(
  name='DetectorType',
  full_name='PB_Event.DetectorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BACKWARD', index=0, number=-1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BARREL', index=1, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORWARD', index=2, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=415,
  serialized_end=477,
)


BACKWARD = -1
BARREL = 0
FORWARD = 1



_PGLOBALPOINT = descriptor.Descriptor(
  name='PGlobalPoint',
  full_name='PB_Event.PGlobalPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='PB_Event.PGlobalPoint.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='PB_Event.PGlobalPoint.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='z', full_name='PB_Event.PGlobalPoint.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=72,
)


_PHIT = descriptor.Descriptor(
  name='PHit',
  full_name='PB_Event.PHit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='position', full_name='PB_Event.PHit.position', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='detectorType', full_name='PB_Event.PHit.detectorType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='layer', full_name='PB_Event.PHit.layer', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='detectorId', full_name='PB_Event.PHit.detectorId', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hitId', full_name='PB_Event.PHit.hitId', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='simTrackID', full_name='PB_Event.PHit.simTrackID', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='simTrackPt', full_name='PB_Event.PHit.simTrackPt', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=75,
  serialized_end=259,
)


_PEVENT = descriptor.Descriptor(
  name='PEvent',
  full_name='PB_Event.PEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='runNumber', full_name='PB_Event.PEvent.runNumber', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lumiSection', full_name='PB_Event.PEvent.lumiSection', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eventNumber', full_name='PB_Event.PEvent.eventNumber', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hits', full_name='PB_Event.PEvent.hits', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=261,
  serialized_end=360,
)


_PEVENTCONTAINER = descriptor.Descriptor(
  name='PEventContainer',
  full_name='PB_Event.PEventContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='events', full_name='PB_Event.PEventContainer.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=362,
  serialized_end=413,
)

_PHIT.fields_by_name['position'].message_type = _PGLOBALPOINT
_PHIT.fields_by_name['detectorType'].enum_type = _DETECTORTYPE
_PEVENT.fields_by_name['hits'].message_type = _PHIT
_PEVENTCONTAINER.fields_by_name['events'].message_type = _PEVENT
DESCRIPTOR.message_types_by_name['PGlobalPoint'] = _PGLOBALPOINT
DESCRIPTOR.message_types_by_name['PHit'] = _PHIT
DESCRIPTOR.message_types_by_name['PEvent'] = _PEVENT
DESCRIPTOR.message_types_by_name['PEventContainer'] = _PEVENTCONTAINER

class PGlobalPoint(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PGLOBALPOINT
  
  # @@protoc_insertion_point(class_scope:PB_Event.PGlobalPoint)

class PHit(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHIT
  
  # @@protoc_insertion_point(class_scope:PB_Event.PHit)

class PEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEVENT
  
  # @@protoc_insertion_point(class_scope:PB_Event.PEvent)

class PEventContainer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEVENTCONTAINER
  
  # @@protoc_insertion_point(class_scope:PB_Event.PEventContainer)

# @@protoc_insertion_point(module_scope)
